/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasreservationtaliscocab;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.System.exit;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author natha
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saldoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        formEventBtn = new javax.swing.JButton();
        formMyEventBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        formParkingBtn = new javax.swing.JButton();
        formMyParkingBtn = new javax.swing.JButton();
        formTopUpBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 450));
        getContentPane().setLayout(null);
        getContentPane().add(saldoTxt);
        saldoTxt.setBounds(180, 70, 200, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Saldo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(177, 38, 35, 18);

        refreshBtn.setBackground(new java.awt.Color(0, 153, 153));
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("REFRESH");
        refreshBtn.setBorder(null);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn);
        refreshBtn.setBounds(10, 360, 160, 28);

        formEventBtn.setBackground(new java.awt.Color(0, 153, 153));
        formEventBtn.setForeground(new java.awt.Color(255, 255, 255));
        formEventBtn.setText("EVENT");
        formEventBtn.setBorder(null);
        formEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formEventBtnActionPerformed(evt);
            }
        });
        getContentPane().add(formEventBtn);
        formEventBtn.setBounds(10, 160, 160, 29);

        formMyEventBtn.setBackground(new java.awt.Color(0, 153, 153));
        formMyEventBtn.setForeground(new java.awt.Color(255, 255, 255));
        formMyEventBtn.setText("MY EVENT");
        formMyEventBtn.setBorder(null);
        formMyEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMyEventBtnActionPerformed(evt);
            }
        });
        getContentPane().add(formMyEventBtn);
        formMyEventBtn.setBounds(10, 200, 160, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome,");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 70, 65, 18);
        getContentPane().add(nameTxt);
        nameTxt.setBounds(10, 100, 153, 29);

        formParkingBtn.setBackground(new java.awt.Color(0, 153, 153));
        formParkingBtn.setForeground(new java.awt.Color(255, 255, 255));
        formParkingBtn.setText("PARKING");
        formParkingBtn.setBorder(null);
        formParkingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formParkingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(formParkingBtn);
        formParkingBtn.setBounds(10, 280, 160, 28);

        formMyParkingBtn.setBackground(new java.awt.Color(0, 153, 153));
        formMyParkingBtn.setForeground(new java.awt.Color(255, 255, 255));
        formMyParkingBtn.setText("MY PARKING");
        formMyParkingBtn.setBorder(null);
        formMyParkingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMyParkingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(formMyParkingBtn);
        formMyParkingBtn.setBounds(10, 320, 160, 28);

        formTopUpBtn.setBackground(new java.awt.Color(0, 153, 153));
        formTopUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        formTopUpBtn.setText("TOP UP");
        formTopUpBtn.setBorder(null);
        formTopUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTopUpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(formTopUpBtn);
        formTopUpBtn.setBounds(10, 240, 160, 28);

        logoutBtn.setBackground(new java.awt.Color(0, 153, 153));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("LOG OUT");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(0, 430, 170, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 395, 466);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formEventBtnActionPerformed
        FormEvent home = new FormEvent();
        home.show();
        dispose();
    }//GEN-LAST:event_formEventBtnActionPerformed

    private void formMyEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMyEventBtnActionPerformed
        FormMyEvent home = new FormMyEvent();
        home.show();
        dispose();
    }//GEN-LAST:event_formMyEventBtnActionPerformed

    private void formParkingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formParkingBtnActionPerformed
        FormParking home = new FormParking();
        home.show();
        dispose();
    }//GEN-LAST:event_formParkingBtnActionPerformed

    private void formMyParkingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMyParkingBtnActionPerformed
        FormMyParking home = new FormMyParking();
        home.show();
        dispose();
    }//GEN-LAST:event_formMyParkingBtnActionPerformed

    private void formTopUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTopUpBtnActionPerformed
        FormTopUp home = new FormTopUp();
        home.show();
        dispose();
    }//GEN-LAST:event_formTopUpBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        
    }//GEN-LAST:event_logoutBtnActionPerformed
    public static String name;
    public static int id_user;
    public static double balance;
    
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        try {
            String hasil;
            
            Socket clientSocket = new Socket("localhost",6666);
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());
            sendToServer.writeBytes("REFRESH~" + "\n");
            
            BufferedReader chatFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            hasil = chatFromServer.readLine();
            System.out.println(hasil);
            
            String[] hasils = hasil.split("~");
            System.out.println(hasils[0]);
            if(hasils[0].equals("TRUE")) {
                name = hasils[1];
                nameTxt.setText(name);
                balance = Double.parseDouble(hasils[2]);
                saldoTxt.setText(Double.toString(balance));
                nameTxt.setText(name);
                
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Refresh!");

            }
        } catch(IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton formEventBtn;
    private javax.swing.JButton formMyEventBtn;
    private javax.swing.JButton formMyParkingBtn;
    private javax.swing.JButton formParkingBtn;
    private javax.swing.JButton formTopUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField saldoTxt;
    // End of variables declaration//GEN-END:variables
}
