/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasreservationtaliscocab;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class FormEvent extends javax.swing.JFrame {

    /**
     * Creates new form FormEvent
     */
    public FormEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvent = new javax.swing.JTable();
        jButtonViewEvent = new javax.swing.JButton();
        jButtonReservationEvent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idEventTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 450));
        setSize(new java.awt.Dimension(900, 450));

        jTableEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id ", "event_name", "event_date", "category", "status", "participant_slot", "number_of_participant", "open_reservation_date", "close_reservation_date", "locations_id ", "price", "description"
            }
        ));
        jScrollPane1.setViewportView(jTableEvent);

        jButtonViewEvent.setText("View");
        jButtonViewEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEventActionPerformed(evt);
            }
        });

        jButtonReservationEvent.setText("Reserve");
        jButtonReservationEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationEventActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity");

        qtyTxt.setText("jTextField1");

        jLabel2.setText("ID Event");

        idEventTxt.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jButtonReservationEvent)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(idEventTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonViewEvent)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonViewEvent)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idEventTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonReservationEvent)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEventActionPerformed
        try {
            String hasil;
            
            Socket clientSocket = new Socket("localhost",6666);
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());
            sendToServer.writeBytes("EVENTVIEW~" + "\n");
            
            BufferedReader chatFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            hasil = chatFromServer.readLine();
            System.out.println(hasil);
            
            DefaultTableModel tableModel = (DefaultTableModel) jTableEvent.getModel();
            tableModel.setRowCount(0);  
            String[] hasils = hasil.split("~");
            
            for (int i = 0; i < hasils.length; i += 12) {
                String[] row = new String[12];
                System.arraycopy(hasils, i, row, 0, 12);
                tableModel.addRow(row);
            }
        } catch(IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButtonViewEventActionPerformed

    private void jButtonReservationEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationEventActionPerformed
        try {
            String hasil;
            int id_event = Integer.parseInt(idEventTxt.getText());
            int quantity = Integer.parseInt(qtyTxt.getText());

            DefaultTableModel tableModel = (DefaultTableModel) jTableEvent.getModel();
            int rowCount = tableModel.getRowCount();
            boolean found = false;

            String eventName = "";
            String eventDate = "";
            String category = "";
            String status = "";
            int participantSlot = 0;
            int numberOfParticipant = 0;
            String openReservationDate = "";
            String closeReservationDate = "";
            int locationsId = 0;
            double price = 0.0;
            String description = "";

            for (int row = 0; row < rowCount; row++) {
                if (Integer.parseInt(String.valueOf(tableModel.getValueAt(row, 0))) == id_event) {
                    found = true;
                    eventName = String.valueOf(tableModel.getValueAt(row, 1));

                    // Ubah format tanggal
                    String rawEventDate = String.valueOf(tableModel.getValueAt(row, 2));
                    SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
                    try {
                        Date date = inputFormat.parse(rawEventDate);
                        eventDate = outputFormat.format(date);
                    } catch (ParseException e) {
                        e.printStackTrace();
                        eventDate = rawEventDate; // Jika parsing gagal, gunakan format asli
                    }

                    category = String.valueOf(tableModel.getValueAt(row, 3));
                    status = String.valueOf(tableModel.getValueAt(row, 4));
                    participantSlot = Integer.parseInt(String.valueOf(tableModel.getValueAt(row, 5)));
                    numberOfParticipant = Integer.parseInt(String.valueOf(tableModel.getValueAt(row, 6)));
                    openReservationDate = String.valueOf(tableModel.getValueAt(row, 7));
                    closeReservationDate = String.valueOf(tableModel.getValueAt(row, 8));
                    locationsId = Integer.parseInt(String.valueOf(tableModel.getValueAt(row, 9)));
                    price = Double.parseDouble(String.valueOf(tableModel.getValueAt(row, 10)));
                    description = String.valueOf(tableModel.getValueAt(row, 11));
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Event ID not found in table.");
                return;
            }

            Socket clientSocket = new Socket("localhost", 6666);
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());

            FormMenu menu = new FormMenu();
            String dataToSend = "EVENTRESERVATION~" 
                + menu.id_user + "~" 
                + id_event + "~" 
                + quantity + "~" 
                + eventName + "~" 
                + eventDate + "~" 
                + category + "~" 
                + status + "~" 
                + participantSlot + "~" 
                + numberOfParticipant + "~" 
                + openReservationDate + "~" 
                + closeReservationDate + "~" 
                + locationsId + "~" 
                + price + "~" 
                + description + "\n";
        
            sendToServer.writeBytes(dataToSend);

            BufferedReader chatFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            hasil = chatFromServer.readLine();
            System.out.println(hasil);

            String[] hasils = hasil.split("~");
            
            if (hasils[0].equals("TRUE")) {
                JOptionPane.showMessageDialog(this, "Reservation successful!");
                FormMenu form = new FormMenu();
                form.balance = Double.parseDouble(hasils[1]);
                System.out.println(form.balance);
            } else {
                JOptionPane.showMessageDialog(this, "Reservation failed, balance insufficient");
                FormMenu form = new FormMenu();
                form.balance = Double.parseDouble(hasils[1]);
                System.out.println(form.balance);
            }
        } catch (IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonReservationEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idEventTxt;
    private javax.swing.JButton jButtonReservationEvent;
    private javax.swing.JButton jButtonViewEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEvent;
    private javax.swing.JTextField qtyTxt;
    // End of variables declaration//GEN-END:variables
}
